<script type="text/javascript" src="<?= JSCORONA; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA0; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA12; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA13; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA1; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA3; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA2; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA5; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA4; ?>"></script>
<script type="text/javascript" src="<?= JSPROFILESETTING; ?>"></script>