<script type="text/javascript" src="<?= JSCORONA0; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA1; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA2; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA3; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA4; ?>"></script>
<script type="text/javascript" src="<?= JSCORONA5; ?>"></script>
<script type="text/javascript" src="<?= JSVALIDATIONREGISTER; ?>"></script>
<script type="text/javascript" src="<?= JSREGISTERAJAX; ?>"></script>
<script type="text/javascript" src="<?= CDNJSGSAP; ?>"></script>
<script type="text/javascript" src="<?= JSANIMATEDREGISTER; ?>"></script>