<script type="text/javascript" src="<?= JSADMIN; ?>"></script>
<script type="text/javascript" src="<?= JSADMIN0; ?>"></script>
<script type="text/javascript" src="<?= JSADMIN1; ?>"></script>
<script type="text/javascript" src="<?= JSADMIN2; ?>"></script>
<script type="text/javascript" src="<?= JSADMIN3; ?>"></script>
<script type="text/javascript" src="<?= JSADMIN4; ?>"></script>
<script type="text/javascript" src="<?= JSADMIN5; ?>"></script>
<script type="text/javascript" src="<?= JSADMIN6; ?>"></script>
<script type="text/javascript" src="<?= JSADMIN7; ?>"></script>
<script type="text/javascript" src="<?= JSADMIN8; ?>"></script>
<script type="text/javascript" src="<?= JSADMIN9; ?>"></script>